### ISSUE TITLE
Plugin not working anymore

### ISSUE THREAD

**Issue by instantgreen** [benjaffe/chrome-okc-plugin#119]
Hey,

I just came back to my PC, didn't restart my PC or Chrome in the meantime, and suddenly the plugin doesn't work anymore. It seems like it can't read or request the pages anymore because the result area stays empty, just like when a person hasn't answered any questions. The site works normally, though. I checked with several profiles which had answered a lot of questions: no results whatsoever. The JavaScript console doesn't seem to show any errors.

Does anybody see this, too?

**Comment by benjaffe** [comment]
BIG sigh... I see it too. :(  And it's not the best timing either, since I have a busy next many days. I'll try and debug the issue when I get a chance, hopefully soon. 

I hope the issue is just a small change with the site. If anyone is able to investigate before I am, let's track this issue in this thread. Thanks @instantgreen for reporting this.

**Comment by benjaffe** [comment]
Fixed it! K, time to go to bed. The fix should be live within the hour.

**Comment by instantgreen** [comment]
It's working! Thanks! :)
