### ISSUE TITLE
Plugin uses lots of RAM while improving accuracy

### ISSUE THREAD

**Issue by instantgreen** [benjaffe/chrome-okc-plugin#129]
Today I started the process of improving the plugin accuracy. What I noticed was that the plugin got slower with each question. When I checked out the chrome process, it had risen to 2.2GB of RAM. Is there anything that could prevent this from happening?

**Comment by benjaffe** [comment]
Oof, that makes sense I think. It's likely because for each question it shows you, it opens a new instance of the site in an iframe. Probably, I'm not properly disposing of them, so the garbage collector isn't collecting them up. I won't have time to look at this within the next 1.5 months though, but it's something worth looking into.

**Comment by benjaffe** [comment]
Due to OkC's regular site updates, I'm removing the "improve accuracy" feature.
