### ISSUE TITLE
profile data and settings do not persist

### ISSUE THREAD

**Issue by Teacheresque** [benjaffe/chrome-okc-plugin#137]
As of today it seems this extension just stopped working completely.

All of my saved profiles and previous annotations to profiles (i.e. "not for me", "not poly", etc.) were erased.

The categories were reset to the default ones, but any attempts to change them don't stick. Loading a new profile or reloading the page resets them to the default ones.

New annotations to profiles also don't save. I can mark a profile using any option and it appears on the profile page, but they disappear upon reloading the page or returning to search.

**Comment by instantgreen** [comment]
Maybe it's a coincidence but something like that happened to me yesterday, too. The plugin didn't seem to work anymore, the categories I chose didn't stick.

I ended up uninstalling and reinstalling the plugin, I also deleted my browser cache. After that it worked agin.

**Comment by Teacheresque** [comment]
Yeah, I deleted my browser cache and uninstalled/reinstalled, and still have the same issues. Categories seem to revert as part of loading a profile page, and the annotations don't save after leaving a profile page.

**Comment by instantgreen** [comment]
This has become a real issue, the plugin keeps the categories for maybe two profile visits and then it's back to the default categories. 

The only thing that seems to help for a bit longer is to reinstall the plugin, although I haven't figured out how long it lasts then.

One observation I made in case of a malfunction is that it doesn't fully revert back to the default categories for me. For some reason "cuddling" won't even be displayed in the "Change categories"-dialogue. Kind of peculiar.

Actually I thought about just changing the default categories in setup.js to everything I usually pick but since "cuddling" gets dropped for some reason, I will still have to reinstall the plugin regularly.

**Comment by benjaffe** [comment]
That's really strange. I'd check to see if localStorage keys get deleted
when it breaks. Maybe OkC is doing something to intentionally break the
plugin, or perhaps localStorage.clear() is being called by them or by
another plugin.

I'm away from my computer until at least late august, so I can't
investigate until then.

**Comment by instantgreen** [comment]
I'd be happy to do some investigation for you but I'm really not well versed in javascript. Opening the console is the only thing I can do. :) 

That being said, the output of localStorage is "Storage {}". If that's what you meant. But I guess you didn't because it's empty even if the plugin is working...

What really suprises me, though, is that websites can delete plugin storages?!

**Comment by EvanCarroll** [comment]
I'm seeing this too. I AM EVAN CARROLL. I'll fix this

**Comment by benjaffe** [comment]
I haven't spent too much time on OkC, but I'm currently not seeing this issue. Categories are sticking on page refreshes, and so are labels for users. Can someone help me out with specific steps to reproduce this issue? I'm wondering if different people are affected more/less by this bug... :/

**Comment by Teacheresque** [comment]
Just tried this out again. What seems to be resetting the profile data is going back to the "browse matches" screen. Changes made to a profile persist when the individual profile page is reloaded, or when going back to the main OKC page (or other pages) then back to the profile page.

**Comment by benjaffe** [comment]
This helps a lot. I can reproduce this issue now.

I've determined that at least on "http://www.okcupid.com/match", localStorage gets cleared out before the plugin has a chance to run. OkC's code runs `localStorage.clear("matchsearchHiddenUsers")`, but `localStorage.clear()` doesn't accept arguments. They need to use `.removeItem()` instead.

I'll reach out to the OkC devs about this. If anybody has contacts for me, I'd appreciate that. Otherwise I'll just bounce around LinkedIn until I find someone.

**Comment by instantgreen** [comment]
I'm on A-list which gives me a guaranteed response from their cusomer service. If anything gets changed is of course unsure. Just craft a message that I can forward. :)

**Comment by mgeraci** [comment]
Thanks for pointing this out, folks! I'll check it out and roll out a fix soon.

**Comment by mgeraci** [comment]
Ok, the fix is out everywhere. Thanks again!

**Comment by benjaffe** [comment]
That was a fast rollout, I'm impressed! Thank you @mgeraci , and kudos to your team. You guys rock.

I'm heading out the door @instantgreen and others, so I'll check later tonight, or if you guys see it fixed, comment here. :)

**Comment by Teacheresque** [comment]
Seems to be fixed on my end, as going back to the browse matches page no longer resets the categories or account flags. Thanks for the quick fix, it's great to have this extension back!

**Comment by instantgreen** [comment]
Yes, seems to be fixed. Great! :)
