### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by instantgreen** [benjaffe/chrome-okc-plugin#161]
Seems like as of this evening the plugin isn't working anymore. It only says "No Results".

**Comment by tfmorris** [comment]
I just noticed it's broken for me as well. It looks like OKC has removed the mobile API, so a request to:

    //www.okcupid.com/profile/<profilename>/questions?n=1&low=1&i_care=1&mobile_app=1

returns

    <meta http-equiv="REFRESH" content="0;url=/profile/<profilename>/questions">

Removing the mobile_app=1 parameter in the query string seems to fix things.  The browser app also appears to be using n=3&low=11/21/31/... where the plugin uses n=1 instead of n=3.

**Comment by tfmorris** [comment]
Removing the `mobile_app=1` parameter allows the GET to complete without the client side redirect, but the contents aren't parseable by the existing code. It looks like `okc_api=1` turns on a JSON API, so that may be the best way forward.

**Comment by benjaffe** [comment]
We should be in business again! Fix is out, 2.9.2
